#!/bin/sh
# 서브모듈 업데이트 여부 확인
git submodule update --remote

# 특정 디렉토리(서브모듈) 내 변경 사항 확인
if git diff --exit-code -- ./16-team6-BE-submodule; then
    exit 0
else
    echo "서브모듈 업데이트 후 변경 사항이 있습니다. 커밋 후 다시 push 해주세요."
    exit 1
fi
