spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

kakao:
  client-id: ${secret.dev.OAUTH_KAKAO_CLIENT_ID}

tmap:
  api:
    app-key: ${secret.dev.TMAP_API_KEY}

redis:
  host: localhost
  port: 6379

open-api:
  api:
    url:
      bus: http://ws.bus.go.kr
      bus-route: http://ws.bus.go.kr/api/rest/busRouteInfo
      bus-position: http://ws.bus.go.kr/api/rest/buspos
      bus-operation: https://topis.seoul.go.kr/map/busMap/selectBusList.do
      gyeonggi-bus: http://apis.data.go.kr/6410000/busstationservice/v2
      gyeonggi-route: http://apis.data.go.kr/6410000/busrouteservice/v2
      gyeonggi-arrival: http://apis.data.go.kr/6410000/busarrivalservice/v2
      gyeonggi-bus-position: http://apis.data.go.kr/6410000/buslocationservice/v2
      subway: http://apis.data.go.kr/1613000/SubwayInfoService
      holiday: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService
    service-key: ${secret.dev.OPEN_API_SERVICE_KEY}

kric:
  api:
    service-key: ${secret.dev.KRIC_SERVICE_KEY}

jwt:
  access:
    secret: ${secret.dev.JWT_ACCESS_SECRET}
    expiration: ${secret.dev.JWT_ACCESS_EXPIRATION_MS}
  refresh:
    secret: ${secret.dev.JWT_REFRESH_SECRET}
    expiration: ${secret.dev.JWT_REFRESH_EXPIRATION_MS}
