spring:
  datasource:
    url: jdbc:mysql://${secret.SPRING_DATABASE_HOST}:${secret.SPRING_DATABASE_PORT}/${secret.SPRING_DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${secret.SPRING_DATABASE_USERNAME}
    password: ${secret.SPRING_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    tracer: trace
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: trace
    com.deepromeet.atcha: DEBUG  # FeignClient 패키지 로깅 활성화
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL

kakao:
  client-id: ${secret.OAUTH_KAKAO_CLIENT_ID}
  api:
    url: https://kapi.kakao.com/
  oauth:
    url: https://kauth.kakao.com/oauth

tmap:
  api:
    url: https://apis.openapi.sk.com
    app-key: ${secret.TMAP_API_KEY}

redis:
  host: localhost
  port: 6379

jwt:
  access:
    secret: ${secret.JWT_ACCESS_SECRET}
  refresh:
    secret: ${secret.JWT_REFRESH_SECRET}

open-api:
    api:
        url:
            bus: http://ws.bus.go.kr
            subway: http://apis.data.go.kr/1613000/SubwayInfoService
            holiday: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService
        service-key: ${secret.OPEN_API_SERVICE_KEY}
kric:
    api:
        url:
            subway: https://openapi.kric.go.kr/openapi/trainUseInfo
        service-key: ${secret.KRIC_SERVICE_KEY}
