spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atcha?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysqluser
    password: mysqlpw
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    tracer: trace
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: trace
    com.deepromeet.atcha: DEBUG  # FeignClient 패키지 로깅 활성화
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL

tmap:
  api:
    url: https://apis.openapi.sk.com
    app-key: ${secret.dev.TMAP_API_KEY}

redis:
    host: redis
    port: 6379

kakao:
  client-id: ${secret.dev.OAUTH_KAKAO_CLIENT_ID}
  api:
    url: https://kapi.kakao.com/
  oauth:
    url: https://kauth.kakao.com/oauth
  local:
    url: https://dapi.kakao.com/v2/local
    key: ${secret.dev.KAKAO_REST_API_KEY}


jwt:
  access:
    secret: ${secret.dev.JWT_ACCESS_SECRET}
  refresh:
    secret: ${secret.dev.JWT_REFRESH_SECRET}

open-api:
  api:
    url:
      bus: http://ws.bus.go.kr
      gyeonggi-bus: http://apis.data.go.kr/6410000/busstationservice/v2
      gyeonggi-route: http://apis.data.go.kr/6410000/busrouteservice/v2
      gyeonggi-arrival: http://apis.data.go.kr/6410000/busarrivalservice/v2
      subway: http://apis.data.go.kr/1613000/SubwayInfoService
      holiday: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService
    service-key: ${secret.dev.OPEN_API_SERVICE_KEY}

kric:
  api:
    url:
      subway: https://openapi.kric.go.kr/openapi/trainUseInfo
    service-key: ${secret.dev.KRIC_SERVICE_KEY}
