name: PROD CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: atcha
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Debug - List submodule folder contents
        run: |
          echo "=== Submodule (16th-team6-BE-submodule) Contents ==="
          ls -Rla ./16th-team6-BE-submodule

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/atcha_prod:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/atcha_prod:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ "Prod A", "Prod B" ]
    env:
      PROD_APP_A_IP: ${{ secrets.PROD_APP_A_IP }}
      PROD_APP_B_IP: ${{ secrets.PROD_APP_B_IP }}
    steps:
      - name: Set host variable based on target
        id: set_host
        run: |
          if [ "${{ matrix.target }}" = "Prod A" ]; then
            echo "HOST=${PROD_APP_A_IP}" >> $GITHUB_ENV
          else
            echo "HOST=${PROD_APP_B_IP}" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v4
      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}

          proxy_host: ${{ secrets.REMOTE_BASTION_IP }}
          proxy_username: ${{ secrets.PROD_USERNAME }}
          proxy_key: ${{ secrets.PROD_SSH_KEY }}
          proxy_port: ${{ secrets.REMOTE_SSH_PORT }}

          source: "./deployment/prod/"
          target: /home/atcha/

      - name: SSH Jump Host to Prod Server and Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ env.HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}

          proxy_host: ${{ secrets.REMOTE_BASTION_IP }}
          proxy_username: ${{ secrets.PROD_USERNAME }}
          proxy_key: ${{ secrets.PROD_SSH_KEY }}
          proxy_port: ${{ secrets.REMOTE_SSH_PORT }}

          script: |
            cd /home/atcha
            rm -rf /home/atcha/data
            mv /home/atcha/deployment/prod/* /home/atcha/
            rm -rf /home/atcha/deployment
            sudo bash ./deploy.sh
