name: PROD CD

on:
  workflow_dispatch:
  pull_request: # TODO push 로 변경
    branches: [ dev ] # TODO main 로 변경

env:
  IMAGE_NAME: atcha
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Debug - List submodule folder contents
        run: |
          echo "=== Submodule (16th-team6-BE-submodule) Contents ==="
          ls -Rla ./16th-team6-BE-submodule

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Copy files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_BASTION_IP }}
          username: ${{ secrets.PROD_APP_USERNAME }}
          key: ${{ secrets.PROD_APP_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            scp -i ${{ secrets.PROD_KEY_PATH }} deploy.sh docker-compose.yml ${{ secrets.PROD_APP_USERNAME }}@${{ secrets.TEST_IP }}:/home/${{ secrets.PROD_APP_USERNAME }}/

      - name: Copy files B
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_BASTION_IP }}
          username: ${{ secrets.PROD_APP_USERNAME }}
          key: ${{ secrets.PROD_APP_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            scp -i ${{ secrets.PROD_KEY_PATH }} deploy.sh docker-compose.yml ${{ secrets.PROD_APP_USERNAME }}@${{ secrets.PROD_APP_B_IP }}:/home/${{ secrets.PROD_APP_USERNAME }}/

      - name: Pull docker and deploy at Prod A
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_APP_A_IP }} #TODO private ip 변경 시 수정
          username: ${{ secrets.PROD_APP_USERNAME }}
          key: ${{ secrets.PROD_APP_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            sudo bash ./deploy.sh

      - name: Pull docker and deploy at Prod B
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_APP_B_IP }} #TODO private ip 변경 시 수정
          username: ${{ secrets.PROD_APP_USERNAME }}
          key: ${{ secrets.PROD_APP_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
             sudo bash ./deploy.sh



