name: PROD CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: atcha
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Debug - List submodule folder contents
        run: |
          echo "=== Submodule (16th-team6-BE-submodule) Contents ==="
          ls -Rla ./16th-team6-BE-submodule

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/atcha_prod:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/atcha_prod:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # matrix를 제거하여 단일 실행으로 변경했습니다.
    steps:
      - uses: actions/checkout@v4

      - name: Copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          # HOST 변수를 따로 설정할 필요 없이 바로 Prod A IP를 참조합니다.
          host: ${{ secrets.PROD_APP_A_IP }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}

          proxy_host: ${{ secrets.REMOTE_BASTION_IP }}
          proxy_username: ${{ secrets.PROD_USERNAME }}
          proxy_key: ${{ secrets.PROD_SSH_KEY }}
          proxy_port: ${{ secrets.REMOTE_SSH_PORT }}

          timeout: 120s
          source: "./deployment/prod/"
          target: /home/atcha/

      - name: SSH Jump Host to Prod Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_APP_A_IP }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}

          proxy_host: ${{ secrets.REMOTE_BASTION_IP }}
          proxy_username: ${{ secrets.PROD_USERNAME }}
          proxy_key: ${{ secrets.PROD_SSH_KEY }}
          proxy_port: ${{ secrets.REMOTE_SSH_PORT }}

          script: |
            cd /home/atcha
            rm -rf /home/atcha/data
            # 복사된 파일들을 /home/atcha로 이동시키고 정리합니다.
            mv /home/atcha/deployment/prod/* /home/atcha/
            rm -rf /home/atcha/deployment
            sudo bash ./deploy.sh
