name: STAGING CD

on:
  workflow_dispatch:
  pull_request: # TODO 변경
    branches: [ dev ] # TODO 변경

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Debug - List submodule folder contents
        run: |
          echo "=== Submodule (16th-team6-BE-submodule) Contents ==="
          ls -Rla ./16th-team6-BE-submodule

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          registry: docker.io
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_TOKEN }}
#
#      - name: Build Docker Image
#        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/atcha_staging:latest .
#
#      - name: Push Docker Image
#        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/atcha_staging:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ "Stag A", "Stag B" ]
    env:
      STAG_APP_A_IP: ${{ secrets.STAG_APP_A_IP }}
      STAG_APP_B_IP: ${{ secrets.STAG_APP_B_IP }}
    steps:
      - name: Set host variable based on target
        id: set_host
        run: |
          if [ "${{ matrix.target }}" = "Stag A" ]; then
            echo "HOST=${STAG_APP_A_IP}" >> $GITHUB_ENV
          else
            echo "HOST=${STAG_APP_B_IP}" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ secrets.STAG_USERNAME }}
          key: ${{ secrets.STAG_SSH_KEY }}
          port: 22

          proxy_host: ${{ secrets.STAG_BASTION_IP }} # Bastion 서버 IP
          proxy_username: ${{ secrets.STAG_USERNAME }} # Bastion 서버의 SSH 사용자
          proxy_key: ${{ secrets.STAG_SSH_KEY }}
          proxy_port: 22

          source: "./deployment/staging/"
          target: /home/atcha/

      - name: SSH Jump Host to Staging Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }} # Staging A or B 서버
          username: ${{ secrets.STAG_USERNAME }}
          key: ${{ secrets.STAG_SSH_KEY }}
          port: 22

          proxy_host: ${{ secrets.STAG_BASTION_IP }}
          proxy_username: ${{ secrets.STAG_USERNAME }}
          proxy_key: ${{ secrets.STAG_SSH_KEY }}
          proxy_port: 22

          script: |
            cd /home/atcha
            rm -rf /home/atcha/data
            mv /home/atcha/deployment/staging/* /home/atcha/
            rm -rf /home/atcha/deployment
#            mv /home/atcha/deployment/staging/data/nginx/* /home/atcha/data/nginx
#            sudo bash ./deploy.sh

